### PR TITLE
Mraa Project to create aar and push to bintray UPM-Test

### PR DESCRIPTION
**Pull request by vintummala**
Signed-off-by: Vineela Tummalapalli <vineela.tummalapalli@intel.com>

### CODE REVIEW

**Comment by fujunwei** [comment]
There is no` libc++_shared.so` binary in output mraa.aar.

**Comment by fujunwei** [comment]
It's crash as follow stack.
Sorry for close it accidentally.

A/DEBUG:     #00 pc 0001c792  /system/lib/libc.so (strlen+18)
A/DEBUG:     #01 pc 00093700  /system/lib/libc.so (__strlen_chk+32)
A/DEBUG:     #02 pc 00017fae  /system/lib/libandroidthings.so (APeripheralManagerClient_openPwm+94)
A/DEBUG:     #03 pc 00014706  /data/app/com.example.upm.androidthings.driversamples-1/lib/x86/libmraa.so (mraa_pman_pwm_init_replace+118)
A/DEBUG:     #04 pc 0000a8c2  /data/app/com.example.upm.androidthings.driversamples-1/lib/x86/libmraa.so (mraa_pwm_init+370)
A/DEBUG:     #05 pc 000008cf  /data/app/com.example.upm.androidthings.driversamples-1/lib/x86/libupmc-buzzer.so (buzzer_init+223)
A/DEBUG:     #06 pc 0002056d  /data/app/com.example.upm.androidthings.driversamples-1/lib/x86/libjavaupm_buzzer.so (_ZN3upm6BuzzerC1Ei+253)
A/DEBUG:     #07 pc 00006bb6  /data/app/com.example.upm.androidthings.driversamples-1/lib/x86/libjavaupm_buzzer.so (Java_upm_1buzzer_javaupm_1buzzerJNI_new_1Buzzer+198)
A/DEBUG:     #08 pc 00020cb2  /data/app/com.example.upm.androidthings.driversamples-1/oat/x86/base.odex (offset 0x10000)

**Comment by fujunwei** [comment]
It will be crashed using pwm, could you please continue to fix it?

**Comment by bjbeare** [comment]
I'm not at all sure what to do with this.
It's useful as an example / howto... but since it copies in MRAA source (basically forks MRAA).. .it would be a bad idea to merge this.

I'm thinking that this probably should be documentation... either on the MRAA github wiki or a page on our github wiki.

What do you think?

**Comment by vintummala** [comment]
Sure Bruce. Documenting this would be good. Will do.

**Pull request closed without merging**
